namespace: "davidban77"
name: "gns3"
version: "1.5.0"
readme: "README.md"
description: "Module to interact with GNS3 server REST API based on gns3fy"
authors:
    - "David Flores <davidflores7_8@hotmail.com>"
dependencies:
license:
    - "MIT"
tags:
    - gns3
    - gns3fy
    - networking
    - rest
    - system
    - netops
repository: "https://github.com/davidban77/ansible-collection-gns3"
documentation: "https://github.com/davidban77/ansible-collection-gns3/blob/master/README.md"
homepage: "https://github.com/davidban77/ansible-collection-gns3"
issues: "https://github.com/davidban77/ansible-collection-gns3/issues"
