---
galaxy_info:
  author: David Flores
  description: Create a GNS3 Lab by creating a project and starting up the nodes
  min_ansible_version: 2.8
  license: "MIT"
  galaxy_tags:
    - gns3
    - gns3fy
    - networking
    - rest
    - system
    - netops
  platforms:
    - name: GenericLinux
      versions:
        - any
dependencies: []
